 
# This is a basic workflow to help you get started with Actions

name: Push to loopy

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to another repository
        uses: Loop3d/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'LoopStructural'
          destination-github-username: 'Loop3D'
          destination-repository-name: 'loopPy'
          user-email: lachlan.grose@monash.edu
